- name: Play that has outer and inner loops
  hosts: localhost
  tasks:
    - include_tasks: tasks/loop_task.yml
      loop:
        - susan
        - joe
        - james
      loop_control:
        loop_var: other_info
